In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

## Create & Read

#### 1D Array

In [4]:
arr1 = np.array([1,2,3,5])
arr1

array([1, 2, 3, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(4,)

In [7]:
arr1.dtype

dtype('int32')

In [8]:
arr1.ndim

1

In [9]:
arr1.size

4

#### 2D Array

In [10]:
arr2 = np.array([[1,4,6],[2,3,5]])
arr2

array([[1, 4, 6],
       [2, 3, 5]])

In [11]:
arr2.ndim

2

#### 3D Array

In [12]:
arr3 = np.array([[[1,4,6],[2,3,5]],[[8,9,4],[1,1,1]],[[1,4,6],[2,3,5]]])
arr3

array([[[1, 4, 6],
        [2, 3, 5]],

       [[8, 9, 4],
        [1, 1, 1]],

       [[1, 4, 6],
        [2, 3, 5]]])

In [13]:
arr3.ndim

3

In [14]:
arr3.shape  # 2 = number of layers , 2 = rows , 3 = columns

(3, 2, 3)

### Create random array

In [15]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.62671563, 0.81026533, 0.89017687],
        [0.35627356, 0.25851662, 0.29759308]],

       [[0.51007668, 0.50542796, 0.02171931],
        [0.29216529, 0.1162298 , 0.76622714]],

       [[0.40085017, 0.89560919, 0.40397823],
        [0.01041971, 0.70700866, 0.9326749 ]]])

In [16]:
randomArr.dtype

dtype('float64')

In [17]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
full = np.full((3,2,3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [19]:
arr3  # Take out first instance of array

array([[[1, 4, 6],
        [2, 3, 5]],

       [[8, 9, 4],
        [1, 1, 1]],

       [[1, 4, 6],
        [2, 3, 5]]])

In [20]:
arr3[0]

array([[1, 4, 6],
       [2, 3, 5]])

In [21]:
arr3[0:2]  # slicing

array([[[1, 4, 6],
        [2, 3, 5]],

       [[8, 9, 4],
        [1, 1, 1]]])

In [22]:
arr3[-1]

array([[1, 4, 6],
       [2, 3, 5]])

### Update & Delete

In [23]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [24]:
a1

array([[[0.88527548, 0.60195845],
        [0.23365119, 0.28975124],
        [0.24331357, 0.92162655]],

       [[0.88432837, 0.9166223 ],
        [0.30128027, 0.97699214],
        [0.87469542, 0.34871215]]])

In [25]:
a2

array([[[0.8570265 , 0.87533692],
        [0.72871902, 0.19853234],
        [0.0910799 , 0.14258119]],

       [[0.67525365, 0.68560934],
        [0.18008676, 0.46542767],
        [0.21066502, 0.45898588]]])

#### Basic Math Operations

In [26]:
np.add(a1, a2)

array([[[1.74230198, 1.47729538],
        [0.96237022, 0.48828358],
        [0.33439347, 1.06420774]],

       [[1.55958203, 1.60223165],
        [0.48136703, 1.44241981],
        [1.08536044, 0.80769803]]])

In [27]:
np.subtract(a1,a2)

array([[[ 0.02824897, -0.27337847],
        [-0.49506783,  0.0912189 ],
        [ 0.15223367,  0.77904536]],

       [[ 0.20907472,  0.23101296],
        [ 0.12119352,  0.51156447],
        [ 0.6640304 , -0.11027373]]])

In [28]:
np.divide(a1,a2)

array([[[1.03296161, 0.68768772],
        [0.32063277, 1.45946621],
        [2.67142987, 6.46387208]],

       [[1.30962398, 1.33694546],
        [1.67297295, 2.09912776],
        [4.15206768, 0.75974483]]])

In [29]:
np.multiply(a1,a2)

array([[[0.75870455, 0.52691646],
        [0.17026607, 0.05752499],
        [0.02216098, 0.13140661]],

       [[0.59714596, 0.62844482],
        [0.05425659, 0.45471917],
        [0.18426773, 0.16005395]]])

In [30]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [31]:
sqrt
abs
power
log
mins
maxs

0.875336924550885

In [32]:
maxs

0.875336924550885

In [33]:
mins

0.23365119490495223

### Update

In [34]:
arr3

array([[[1, 4, 6],
        [2, 3, 5]],

       [[8, 9, 4],
        [1, 1, 1]],

       [[1, 4, 6],
        [2, 3, 5]]])

In [35]:
arr3[0][0][2] = 500

In [36]:
arr3

array([[[  1,   4, 500],
        [  2,   3,   5]],

       [[  8,   9,   4],
        [  1,   1,   1]],

       [[  1,   4,   6],
        [  2,   3,   5]]])

In [37]:
arr3.shape

(3, 2, 3)

In [38]:
arr3_reshape = arr3.reshape((2,3,-1))

In [39]:
arr3_reshape

array([[[  1,   4, 500],
        [  2,   3,   5],
        [  8,   9,   4]],

       [[  1,   1,   1],
        [  1,   4,   6],
        [  2,   3,   5]]])

#### Appending and Inserting

In [40]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [41]:
# Create a new array
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [43]:
appd = np.append(zeros, new_array, axis = 0)  # axis 0 = row, axis 1 = column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### Delete

In [44]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.27266416, 0.91441907, 0.1891369 ],
        [0.755598  , 0.07036659, 0.80158974]],

       [[0.65424129, 0.51335012, 0.44407101],
        [0.86458805, 0.95688906, 0.808936  ]],

       [[0.63642027, 0.56109856, 0.546385  ],
        [0.07358558, 0.23467014, 0.81525484]]])

In [46]:
# delete the array
arr5 = np.delete(arr4, 0, axis= 1)

In [47]:
arr5

array([[[0.755598  , 0.07036659, 0.80158974]],

       [[0.86458805, 0.95688906, 0.808936  ]],

       [[0.07358558, 0.23467014, 0.81525484]]])

In [48]:
np.save("new_array", arr5)

In [49]:
np.load("new_array.npy")

array([[[0.755598  , 0.07036659, 0.80158974]],

       [[0.86458805, 0.95688906, 0.808936  ]],

       [[0.07358558, 0.23467014, 0.81525484]]])